mysql:
  build: $DB_DOCKERFILE_DIR
  ports:
    - "13306:3306"
  environment:
    MYSQL_DATABASE : myapp_development
    MYSQL_USER : myapp
    MYSQL_PASSWORD : myapp_pass
    MYSQL_ROOT_PASSWORD : _root_

webapp:
  build: $WEBAPP_DOCKERFILE_DIR
  ports:
    - "80:8080"
    - "3000:3000"
  links:
    - mysql:mysql
  volumes:
    - ${APP_ROOT_DIR}:/var/data
  environment:
    RAILS_DATABASE_HOST : mysql
  command: /var/scripts/start_webapp.sh
#  command: sh -c "cd /var/data && bundle install && bundle exec rails s -b 0.0.0.0 --pid /tmp/puma.pid"


